apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

commonLabels:
  app.kubernetes.io/managed-by: argocd

resources:
- all.yaml
- kustomize-resource-namespace-gitea.yaml
- kustomize-resource-serviceaccount-gitea.yaml
- kustomize-resource-route-gitea.yaml
- kustomize-resource-scc-gitea.yaml

patches:
- path: kustomize-patch-statefulset-gitea.yaml
- path: kustomize-patch-statefulset-gitea-postgresql.yaml