apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

bases:
- ../../helm_base

commonLabels:
  app.kubernetes.io/managed-by: argocd

resources:
  - namespace.yaml
  - base/base-route-gitea.yaml
  - base/base-scc-gitea.yaml
  - base/base-serviceaccount-gitea.yaml

patches:
- path: patch/patch-statefulset-gitea.yaml
- path: patch/patch-statefulset-gitea-postgresql.yaml