apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

bases:
- ../../helm_base

commonLabels:
  app.kubernetes.io/managed-by: argocd

resources:
  - namespace.yml
  - base/base-route-gitea.yml
  - base/base-scc-gitea.yml
  - base/base-serviceaccount-gitea.yml

patches:
- path: patch/patch-statefulset-gitea.yml
- path: patch/patch-statefulset-gitea-postgresql.yml