apiVersion: operators.coreos.com/v1
kind: OperatorGroup
metadata:
  generateName: openshift-cnv-
  namespace: openshift-cnv
spec:
  targetNamespaces:
    - openshift-cnv
  namespaces:
    - openshift-cnv
