# Creates a ManagedClusterSetBinding to the openshift-gitops project
---
apiVersion: cluster.open-cluster-management.io/v1alpha1
kind: ManagedClusterSetBinding
metadata:
  name: local-openshift-clusters
  namespace: openshift-gitops
spec:
  clusterSet: local-openshift-clusters
