apiVersion: cluster.open-cluster-management.io/v1alpha1
kind: Placement
metadata:
  name: local-openshift-clusters
  namespace: openshift-gitops
spec:
  predicates:
  - requiredClusterSelector:
      labelSelector:
        matchExpressions:
        - key: cluster.open-cluster-management.io/clusterset
          operator: "In"
          values:
          - local-openshift-clusters
