allowHostPorts: true
priority: null
requiredDropCapabilities: null
allowPrivilegedContainer: true
runAsUser:
  type: RunAsAny
users:
  - 'system:serviceaccount:gitea-dev:gitea-dev'
  - 'system:serviceaccount:gitea-dev:gitea-dev-memcached'
allowHostDirVolumePlugin: true
seccompProfiles:
  - '*'
allowHostIPC: true
seLinuxContext:
  type: RunAsAny
readOnlyRootFilesystem: false
metadata:
  name: app-gitea-dev
fsGroup:
  type: RunAsAny
kind: SecurityContextConstraints
defaultAddCapabilities: null
allowedUnsafeSysctls:
  - '*'
supplementalGroups:
  type: RunAsAny
volumes:
  - '*'
allowHostPID: true
allowHostNetwork: true
allowPrivilegeEscalation: true
apiVersion: security.openshift.io/v1
allowedCapabilities:
  - '*'
