apiVersion: apps/v1
kind: Deployment
metadata:
  name: console-deployment
  namespace: kube-system
  labels:
    app: console
spec:
  replicas: 1
  selector:
    matchLabels:
      app: console
  template:
    metadata:
      labels:
        app: console
    spec:
      containers:
        - name: console-app
          image: quay.io/openshift-release-dev/ocp-v4.0-art-dev@sha256:54b648e638df420a1750d641b7c66d6a9af972a066f4fbd14ca0d85e19b88d47
          ports:
            - containerPort: 9000
          env:
            - name: BRIDGE_USER_AUTH
              value: disabled # no authentication required
            - name: BRIDGE_K8S_MODE
              value: off-cluster
            - name: BRIDGE_K8S_MODE_OFF_CLUSTER_ENDPOINT
              value: https://kubernetes.default #master api
            - name: BRIDGE_K8S_MODE_OFF_CLUSTER_SKIP_VERIFY_TLS
              value: "true" # no tls enabled
            - name: BRIDGE_K8S_AUTH
              value: bearer-token
            - name: BRIDGE_K8S_AUTH_BEARER_TOKEN
              valueFrom:
                secretKeyRef:
                  name: console-token-zhv2f # console serviceaccount token
                  key: token
---
kind: Service
apiVersion: v1
metadata:
  name: console-ci-service
  namespace: kube-system
spec:
  ports:
    - name: http
      protocol: TCP
      port: 9000
  selector:
    app: console
  type: ClusterIP
---
kind: Route
apiVersion: route.openshift.io/v1
metadata:
  name: console
  namespace: kube-system
spec:
  host: console.microshift.colbert.def
  to:
    kind: Service
    name: console-ci-service
    weight: 100
  port:
    targetPort: http
  wildcardPolicy: None
