apiVersion: operators.coreos.com/v1alpha1
kind: CatalogSource
metadata:
  name: community-operator-index
  namespace: olm
spec:
  displayName: Red Hat Community Operators
  image: 'registry.redhat.io/redhat/community-operator-index:v4.9'
  publisher: Red Hat
  sourceType: grpc
  updateStrategy:
    registryPoll:
      interval: 60m
---
apiVersion: operators.coreos.com/v1alpha1
kind: CatalogSource
metadata:
  name: redhat-operator-index
  namespace: olm
spec:
  displayName: Red Hat Operators
  image: 'registry.redhat.io/redhat/redhat-operator-index:v4.9'
  publisher: Red Hat
  sourceType: grpc
  updateStrategy:
    registryPoll:
      interval: 60m
---
apiVersion: operators.coreos.com/v1alpha1
kind: CatalogSource
metadata:
  name: certified-operator-index
  namespace: olm
spec:
  displayName: Red Hat Certified Operators
  image: 'registry.redhat.io/redhat/certified-operator-index:v4.9'
  publisher: Red Hat
  sourceType: grpc
  updateStrategy:
    registryPoll:
      interval: 60m
