apiVersion: argoproj.io/v1alpha1
kind: ApplicationSet
metadata:
  name: gitea
  namespace: openshift-gitops
spec:
  generators:
  - list:
      # Parameters are generated based on this cluster list, to be
      # substituted into the template below.
      elements: 
      - cluster: core-dev
        url: 'https://kubernetes.default.svc'
      #- cluster: core-colbert-preprod
      #  url: https://2.4.6.8
      #- cluster: core-colbert-prod
      #  url: https://9.8.7.6

  # 'template' is an Argo CD Application template, with support 
  # for parameter substitution using parameters generated above.
  template: 
    metadata:
      # The 'cluster' parameter from above is substituted here
      name: 'gitea'
    spec:
      project: '{{cluster}}'
      source:
        repoURL: 'https://github.com/spanghf37/kickstart-openshift.git'
        targetRevision: HEAD
        # 'cluster' name is also substituted here
        path: openshift-sno/argocd/kustomized_helm-gitea/overlays/{{cluster}}
        plugin:
          name: kustomized-helm
      destination:
        # The cluster 'url', used by Argo CD to access the cluster, is 
        # substituted here.
        server: '{{url}}'
        namespace: 'gitea'
